site_name: Barycentre
nav:
  - ä¸»é¡µ: index.md
  - å·´é™¢æ®µå­:
      - å·´é™¢å’ŒACMè°ä¸äº‰é”‹: joke/SPEIT_VS_ACM.md
      - ä¸è¿‡æ˜¯è€ƒDSå‰çš„å¹»æƒ³ç½¢äº†: joke/Jokes_of_SPEIT.md
      - CTIè®¤è¯ = 6000ä¸‡: joke/Value_of_CTI.md
      - å®ä¹ æ€æ‰‹: joke/SPEIT_internship_killer.md
  - ç”Ÿå­˜æ‰‹å†Œ:
      - å·´é™¢æ•™è‚²ä½“ç³»çš„ç½ªä¸ç½š: survive/Education_at_SPEIT.md
      - æ˜¯å¦è¦è€ƒconcours(WIPğŸš§): survive/Life_at_X.md
      - å¤–ä¼å®ä¹ ä¸€äºŒäº‹: survive/Intern_international_company.md
